[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; Explicit hardware flags for native USB CDC on ESP32-C3
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

; Required flash settings for ESP32-C3 SuperMini modules
board_build.flash_mode = dio

; Add a hardware reset trigger to kick the chip out of bootloader mode after opening the serial monitor
monitor_dtr = 0
monitor_rts = 0

lib_ldf_mode = deep+

lib_deps =
    adafruit/Adafruit SHT4x Library @ ^1.0.4
    claws/BH1750 @ ^1.3.0
    bblanchon/ArduinoJson @ ^7.0.0
